trigger:
- master

strategy:
  matrix:
    linux36:
      imageName: 'ubuntu-16.04'
      python.version: '3.6'
      tox.env: py36
    linux37:
      imageName: 'ubuntu-16.04'
      python.version: '3.7'
      tox.env: py37
    mac36:
      imageName: 'macos-10.13'
      python.version: '3.6'
      tox.env: py36
    mac37:
      imageName: 'macos-10.13'
      python.version: '3.7'
      tox.env: py37
    windows36:
      imageName: 'vs2017-win2016'
      python.version: '3.6'
      tox.env: py36
    windows37:
      imageName: 'vs2017-win2016'
      python.version: '3.7'
      tox.env: py37

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: '$(python.version)'

- script: |
    python -m pip install --disable-pip-version-check --upgrade pip
    python -m pip install tox
    python -m pip install --editable .
  displayName: 'dependencies'

- script: |
    tox -e $(tox.env)
  displayName: 'test'